number = int(input("Podaj liczbę: "))
number2 = int(input("Podaj inną liczbę: "))
print("number + number2 = ", number + number2)
print("number / number2 = "  , number / number2)
print("number * number2 = " , number*number2)
print("number - number2 = ", number-number2)
print("number % number2 = ", number%number2)
